smartlink/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from django.conf import settings
from django.conf.urls.static import static



from apps.smartlink import views

from django.urls import reverse_lazy
from django.contrib.auth.views import (
    
    LoginView,
    LogoutView,
    PasswordResetView,
    PasswordResetDoneView,
    PasswordChangeView,
    PasswordChangeDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView
)

#from django.contrib.auth.views import (
#    login, logout, password_reset, password_reset_done, password_reset_confirm,
#    password_reset_complete
#)

app_name = "smartlink"
urlpatterns = [
    
    url(r'^admin/', admin.site.urls),
    url(r'^evento/(?P<pk>\d+)/$',views.evento,name="evento"),
    url(r'^historial/(?P<pk>\d+)/$',views.agregareventoacliente,name="agregareventoacliente"),
    url(r'^historialn/(?P<pk>\d+)/$',views.quitarevento,name="quitarevento"),
    
    url(r'^$',views.home,name="index"),
    url(r'^email-users/$',views.SendUserEmails.as_view(),name="email"),
    #url(r'^login/$',views.login,name="login"),
    #url(r'^registro/$',views.registro,name="registro"),
    url(r'^login/$', LoginView.as_view(template_name='accounts/login.html'), name='login'),
    # LoginView.as_view(template_name='accounts/login.html'), name='login'),
    #url(r'^logout/$', LogoutView.as_view(next_page=reverse_lazy('login')), name='logout'),
    url(r'^logout/$', LogoutView.as_view(next_page=reverse_lazy('index')), name='logout'),
    url(r'^historial/$', views.historial, name='historial'),
    url(r'^nosotros/$', views.nosotros, name='nosotros'),
    #url(r'^login/$', login, {'template_name': 'accounts/login.html'}, name='login'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^register/$', views.register, name='register'),
    url(r'^profile/$', views.view_profile, name='view_profile'),
    #url(r'^profile/(?P<pk>\d+)/$', views.view_profile, name='view_profile_with_pk'),
    url(r'^profile/edit_profile/$', views.edit_profile, name='edit_profile'),
    url(r'^profile/edit_profile/password/$', views.change_password, name='change_password'),

    #url(r'^reset-password/$', password_reset, {'template_name': 'accounts/reset_password.html', 'post_reset_redirect': 'accounts:password_reset_done', 'email_template_name': 'accounts/reset_password_email.html'}, name='reset_password'),

    #url(r'^reset-password/done/$', password_reset_done, {'template_name': 'accounts/reset_password_done.html'}, name='password_reset_done'),

    #url(r'^reset-password/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', password_reset_confirm, {'template_name': 'accounts/reset_password_confirm.html', 'post_reset_redirect': 'accounts:password_reset_complete'}, name='password_reset_confirm'),

    #url(r'^reset-password/complete/$', password_reset_complete,{'template_name': 'accounts/reset_password_complete.html'}, name='password_reset_complete')
    #url(r'^', include('smartlink.urls')),






]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

templates/accounts/change_password.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="description" content="">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- The above 4 meta tags *must* come first in the head; any other head content must come *after* these tags -->

    <!-- Title -->
    <title>Smart link</title>

    <!-- Favicon -->
   

    <!-- Core Stylesheet -->
    <link href="{% static 'style.css' %}" rel="stylesheet">

    <!-- Responsive CSS -->
    <link href="{% static 'css/responsive.css' %}" rel="stylesheet">

</head>

<body>
    <!-- ***** Preloader Start ***** -->
    <div id="preloader">
        <div class="mosh-preloader"></div>
    </div>

    <!-- ***** Header Area Start ***** -->
    <header class="header_area clearfix">
        <div class="container-fluid h-100">
            <div class="row h-100">
                <!-- Menu Area Start -->
                <div class="col-12 h-100">
                    <div class="menu_area h-100">
                        <nav class="navbar h-100 navbar-expand-lg align-items-center">
                            <!-- Logo 
                            <a class="navbar-brand" href="index.html"><img src="{% static 'img/core-img/logo.png' %}" alt="logo"></a>-->
                            <p> LOGO SMARTLINK  </p>

                            <!-- Menu Area -->
                            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#mosh-navbar" aria-controls="mosh-navbar" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                            
                    



                            <div class="collapse navbar-collapse justify-content-end" id="mosh-navbar">
                                    {% if user.is_authenticated %}
                                <ul class="navbar-nav animated" id="nav">
                                        <li class="nav-item active"><a class="nav-link" >Bienvenido  {{ user }}</a></li>
                                    <li class="nav-item active"><a class="nav-link" href="/">Inicio</a></li>
                                    <li class="nav-item active"><a class="nav-link" href="/profile/edit_profile">Editar perfil</a></li>
                                    
                                   
                                    <li class="nav-item"><a class="nav-link" href="/logout">Cerrar sesion</a></li>
                                    <!-- <li class="nav-item"><a class="nav-link" href="blog.html">Blog</a></li>
                                    <li class="nav-item"><a class="nav-link" href="contact.html">Contact</a></li>-->
                                </ul>
                             
                                <!-- Search Form Area Start -->
                                <!--<div class="search-form-area animated">
                                    <form action="#" method="post">
                                        <input type="search" name="search" id="search" placeholder="Type keywords &amp; hit enter">
                                        <button type="submit" class="d-none"><img src="{% static 'img/core-img/search-icon.png' %}" alt="Search"></button>
                                    </form>
                                </div>-->
                                <!-- Search btn -->
                                <!--div class="search-button">
                                    <a href="#" id="search-btn"><img src="{% static 'img/core-img/search-icon.png' %}" alt="Search"></a>
                                </div>-->
                                <!-- Login/Register btn -->
                                {% else %}
                                <ul class="navbar-nav animated" id="nav">
                                        <li class="nav-item active"><a class="nav-link" href="/">Inicio</a></li>
                                     
                                        <li class="nav-item"><a class="nav-link" href="#eventos_generales">Eventos generales</a></li>
                               
                                        <!-- <li class="nav-item"><a class="nav-link" href="blog.html">Blog</a></li>
                                        <li class="nav-item"><a class="nav-link" href="contact.html">Contact</a></li>-->
                                    </ul>

                                <div class="login-register-btn">
                                    <a href="login" >Iniciar sesion</a>
                                    <a href="register">/ Registrarme</a>
                                </div>
                                {% endif %}
                            </div>
                        </nav>
                    </div>
                </div>
            </div>
        </div>
    </header>
    <!-- ***** Header Area End ***** -->

    <!-- ***** Welcome Area Start ***** -->
    <section class="welcome_area clearfix" id="home" style="background-image: url(/static/img/bg-img/welcome-bg.png); padding-top:150px;">
        



        <div class="container">
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit">Guardar</button>
                </form>
                <br>
            </div>
            
           
       
    </section>
    <!-- ***** Welcome Area End ***** -->

    
    <!-- ***** CTA Area Start ***** 
    <section class="mosh-call-to-action-area bg-img bg-overlay section_padding_100" style="background-image: url(img/bg-img/cta.jpg);">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <div class="cta-content text-center wow fadeIn" data-wow-delay="0.5s">
                        <div class="section-heading">
                            <p>give us a shout</p>
                            <h2>Are you Ready to have a Talk?</h2>
                            <a href="contact.html" class="btn mosh-btn">Contact Us</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>-->
    <!-- ***** CTA Area End ***** -->

    <!-- ***** Footer Area Start ***** -->
    <footer class="footer-area clearfix">
        <!-- Top Fotter Area -->
        <div class="top-footer-area section_padding_100_0">
            <div class="container">
                <div class="row">
                    <div class="col-12 col-sm-6 col-lg-3">
                        <div class="single-footer-widget mb-100">
                            <P>LOGO SMARTLINK</P>>
                            <!-- LOGOOO  <a href="#" class="mb-50 d-block"><img src="{% static 'img/core-img/logo.png' %}" alt=""></a>-->
                            <p>DESCRIPCIOÓN</p>
                        </div>
                    </div>
                    <div class="col-12 col-sm-6 col-lg-3">
                        <div class="single-footer-widget mb-100">
                            <h5>Links de interes</h5>
                            <ul>
                                <li><a href="#">**********</a></li>
                                <li><a href="#">**********</a></li>
                                <li><a href="#">**********</a></li>
                                <li><a href="#">**********</a></li>
                                <li><a href="#">**********</a></li>
                            </ul>
                        </div>
                    </div>
                    <!--
                    <div class="col-12 col-sm-6 col-lg-3">
                        <div class="single-footer-widget mb-100">
                            <h5>Blog</h5>
                            <div class="footer-single--blog-post">
                                <a href="#" class="blog-post-date">
                                    <p>23 September, 2017</p>
                                </a>
                                <a href="#" class="blog-post-title">
                                    <h6>Why we love stock photos</h6>
                                </a>
                            </div>
                            <div class="footer-single--blog-post">
                                <a href="#" class="blog-post-date">
                                    <p>22 September, 2017</p>
                                </a>
                                <a href="#" class="blog-post-title">
                                    <h6>Designin on grid. A few rules. </h6>
                                </a>
                            </div>
                            <div class="footer-single--blog-post">
                                <a href="#" class="blog-post-date">
                                    <p>20 September, 2017</p>
                                </a>
                                <a href="#" class="blog-post-title">
                                    <h6>2017 World Design Congress</h6>
                                </a>
                            </div>
                        </div>
                    </div>
                    -->
                    <div class="col-12 col-sm-6 col-lg-3">
                        <div class="single-footer-widget mb-100">
                            <h5>Informacion de contacto</h5>
                            <div class="footer-single-contact-info d-flex">
                                <div class="contact-icon">
                                    <img src="{% static 'img/core-img/map.png' %}" alt="">
                                </div>
                                <p>DIRECCION</p>
                            </div>
                            <div class="footer-single-contact-info d-flex">
                                <div class="contact-icon">
                                    <img src="{% static 'img/core-img/call.png' %}" alt="">
                                </div>
                                <p>T3C: 77777777 <br> EXTENSION: 777777777</p>
                            </div>
                            <div class="footer-single-contact-info d-flex">
                                <div class="contact-icon">
                                    <img src="{% static 'img/core-img/message.png' %}" alt="">
                                </div>
                                <p>oficina@oficina.com</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Fotter Bottom Area -->
        <div class="footer-bottom-area">
            <div class="container h-100">
                <div class="row h-100">
                    <div class="col-12 h-100">
                        <div class="footer-bottom-content h-100 d-md-flex justify-content-between align-items-center">
                            <div class="copyright-text">
                                <p><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
<a>TERMINIOS & CONDICIONES DE SERVICIO</a>
<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
</p>
                            </div>
                            <div class="footer-social-info">
                                <a href="#"><i class="fa fa-pinterest" aria-hidden="true"></i></a>
                                <a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a>
                                <a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a>
                                <a href="#"><i class="fa fa-dribbble" aria-hidden="true"></i></a>
                                <a href="#"><i class="fa fa-behance" aria-hidden="true"></i></a>
                                <a href="#"><i class="fa fa-linkedin" aria-hidden="true"></i></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <!-- ***** Footer Area End ***** -->

    <!-- jQuery-2.2.4 js -->
    <script type="text/javascript" src="{% static 'js/jquery-2.2.4.min.js' %}"></script>
    <!-- Popper js -->
    <script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
    <!-- Bootstrap js -->
    <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
    <!-- All Plugins js -->
    <script type="text/javascript" src="{% static 'js/plugins.js' %}"></script>
    <!-- Active js -->
    <script type="text/javascript" src="{% static 'js/active.js' %}"></script>
</body>

</html>

templates/accounts/edit_profile.html
{% load static %}
{% load crispy_forms_tags %}


<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="description" content="">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- The above 4 meta tags *must* come first in the head; any other head content must come *after* these tags -->

    <!-- Title -->
    <title>Smart link</title>

    <!-- Favicon -->
   

    <!-- Core Stylesheet -->
    <link href="{% static 'style.css' %}" rel="stylesheet">
   

    <!-- Responsive CSS -->
    <link href="{% static 'css/responsive.css' %}" rel="stylesheet">

</head>

<body>
    <!-- ***** Preloader Start ***** -->
    <div id="preloader">
        <div class="mosh-preloader"></div>
    </div>

    <!-- ***** Header Area Start ***** -->
    <header class="header_area clearfix">
        <div class="container-fluid h-100">
            <div class="row h-100">
                <!-- Menu Area Start -->
                <div class="col-12 h-100">
                    <div class="menu_area h-100">
                        <nav class="navbar h-100 navbar-expand-lg align-items-center">
                                <a class="navbar-brand" href="/"><img src="{% static 'img/core-img/logo.png' %}" alt="logo"></a>

                            <!-- Menu Area -->
                            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#mosh-navbar" aria-controls="mosh-navbar" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                            
                    



                            <div class="collapse navbar-collapse justify-content-end" id="mosh-navbar">
                                    {% if user.is_authenticated %}
                                <ul class="navbar-nav animated" id="nav">
                                        <li class="nav-item active"><a class="nav-link" >Bienvenido  {{ user }}</a></li>
                                    <li class="nav-item active"><a class="nav-link" href="/">Inicio</a></li>
                                    <li class="nav-item"><a class="nav-link" href="/profile">Mi perfil</a></li>

                                   
                                    <li class="nav-item"><a class="nav-link" href="/logout">Cerrar sesion</a></li>
                                    <!-- <li class="nav-item"><a class="nav-link" href="blog.html">Blog</a></li>
                                    <li class="nav-item"><a class="nav-link" href="contact.html">Contact</a></li>-->
                                </ul>
                             
                                <!-- Search Form Area Start -->
                                <!--<div class="search-form-area animated">
                                    <form action="#" method="post">
                                        <input type="search" name="search" id="search" placeholder="Type keywords &amp; hit enter">
                                        <button type="submit" class="d-none"><img src="{% static 'img/core-img/search-icon.png' %}" alt="Search"></button>
                                    </form>
                                </div>-->
                                <!-- Search btn -->
                                <!--div class="search-button">
                                    <a href="#" id="search-btn"><img src="{% static 'img/core-img/search-icon.png' %}" alt="Search"></a>
                                </div>-->
                                <!-- Login/Register btn -->
                                {% else %}
                                <ul class="navbar-nav animated" id="nav">
                                        <li class="nav-item active"><a class="nav-link" href="#home">Inicio</a></li>
                                     
                                        <li class="nav-item"><a class="nav-link" href="#eventos_generales">Eventos generales</a></li>
                               
                                        <!-- <li class="nav-item"><a class="nav-link" href="blog.html">Blog</a></li>
                                        <li class="nav-item"><a class="nav-link" href="contact.html">Contact</a></li>-->
                                    </ul>

                                <div class="login-register-btn">
                                    <a href="login" >Iniciar sesion</a>
                                    <a href="register">/ Registrarme</a>
                                </div>
                                {% endif %}
                            </div>
                        </nav>
                    </div>
                </div>
            </div>
        </div>
    </header>
    <!-- ***** Header Area End ***** -->

    <!-- ***** Welcome Area Start ***** -->
    <section class="welcome_area clearfix" id="home" style="background-image: url(/static/img/bg-img/welcome-bg.png); padding-top:150px;">
      

        <div class="container">
                <form style="color:black; font-size: 20px; font-family: sans-serif" method="post">
                    {% csrf_token %}
                    
                    {{ form.as_table }}
                    {{profile_form|crispy }}
                    
                    
                    <button type="submit"  style="cursor:pointer; margin:0 auto; display: block; margin-bottom: 50px;"  class="btn btn-primary">Actualizar</button>
                </form>
                <br>
            </div>
            
           
       
    </section>
    <!-- ***** Welcome Area End ***** -->

    
    <!-- ***** CTA Area Start ***** 
    <section class="mosh-call-to-action-area bg-img bg-overlay section_padding_100" style="background-image: url(img/bg-img/cta.jpg);">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <div class="cta-content text-center wow fadeIn" data-wow-delay="0.5s">
                        <div class="section-heading">
                            <p>give us a shout</p>
                            <h2>Are you Ready to have a Talk?</h2>
                            <a href="contact.html" class="btn mosh-btn">Contact Us</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>-->
    <!-- ***** CTA Area End ***** -->
 <!-- ***** Workflow Area Start ***** -->
 
    
    <!-- ***** Footer Area Start ***** -->
    <!--
    <footer class="footer-area clearfix">
        
        <div class="top-footer-area section_padding_100_0">
            <div class="container">
                <div class="row">
                    <div class="col-12 col-sm-6 col-lg-3">
                        <div class="single-footer-widget mb-100">
                            <P>LOGO SMARTLINK</P>>
                             LOGOOO  <a href="#" class="mb-50 d-block"><img src="{% static 'img/core-img/logo.png' %}" alt=""></a>
                            <p>DESCRIPCIOÓN</p>
                        </div>
                    </div>
                    <div class="col-12 col-sm-6 col-lg-3">
                        <div class="single-footer-widget mb-100">
                            <h5>Links de interes</h5>
                            <ul>
                                <li><a href="#">**********</a></li>
                                <li><a href="#">**********</a></li>
                                <li><a href="#">**********</a></li>
                                <li><a href="#">**********</a></li>
                                <li><a href="#">**********</a></li>
                            </ul>
                        </div>
                    </div>
                    
                    <div class="col-12 col-sm-6 col-lg-3">
                        <div class="single-footer-widget mb-100">
                            <h5>Blog</h5>
                            <div class="footer-single--blog-post">
                                <a href="#" class="blog-post-date">
                                    <p>23 September, 2017</p>
                                </a>
                                <a href="#" class="blog-post-title">
                                    <h6>Why we love stock photos</h6>
                                </a>
                            </div>
                            <div class="footer-single--blog-post">
                                <a href="#" class="blog-post-date">
                                    <p>22 September, 2017</p>
                                </a>
                                <a href="#" class="blog-post-title">
                                    <h6>Designin on grid. A few rules. </h6>
                                </a>
                            </div>
                            <div class="footer-single--blog-post">
                                <a href="#" class="blog-post-date">
                                    <p>20 September, 2017</p>
                                </a>
                                <a href="#" class="blog-post-title">
                                    <h6>2017 World Design Congress</h6>
                                </a>
                            </div>
                        </div>
                    </div>
                    
                    <div class="col-12 col-sm-6 col-lg-3">
                        <div class="single-footer-widget mb-100">
                            <h5>Informacion de contacto</h5>
                            <div class="footer-single-contact-info d-flex">
                                <div class="contact-icon">
                                    <img src="{% static 'img/core-img/map.png' %}" alt="">
                                </div>
                                <p>DIRECCION</p>
                            </div>
                            <div class="footer-single-contact-info d-flex">
                                <div class="contact-icon">
                                    <img src="{% static 'img/core-img/call.png' %}" alt="">
                                </div>
                                <p>T3C: 77777777 <br> EXTENSION: 777777777</p>
                            </div>
                            <div class="footer-single-contact-info d-flex">
                                <div class="contact-icon">
                                    <img src="{% static 'img/core-img/message.png' %}" alt="">
                                </div>
                                <p>oficina@oficina.com</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="footer-bottom-area">
            <div class="container h-100">
                <div class="row h-100">
                    <div class="col-12 h-100">
                        <div class="footer-bottom-content h-100 d-md-flex justify-content-between align-items-center">
                            <div class="copyright-text">
                                <p>
<a>TERMINIOS & CONDICIONES DE SERVICIO</a>

</p>
                            </div>
                            <div class="footer-social-info">
                                <a href="#"><i class="fa fa-pinterest" aria-hidden="true"></i></a>
                                <a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a>
                                <a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a>
                                <a href="#"><i class="fa fa-dribbble" aria-hidden="true"></i></a>
                                <a href="#"><i class="fa fa-behance" aria-hidden="true"></i></a>
                                <a href="#"><i class="fa fa-linkedin" aria-hidden="true"></i></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </footer>

-->
    <!-- ***** Footer Area End ***** -->

    <!-- jQuery-2.2.4 js -->
    <script type="text/javascript" src="{% static 'js/jquery-2.2.4.min.js' %}"></script>
    <!-- Popper js -->
    <script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
    <!-- Bootstrap js -->
    <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
    <!-- All Plugins js -->
    <script type="text/javascript" src="{% static 'js/plugins.js' %}"></script>
    <!-- Active js -->
    <script type="text/javascript" src="{% static 'js/active.js' %}"></script>
</body>

</html>

templates/accounts/logout.html
{% extends 'base.html' %}

{% block body %}
<div class="container">
    <h1>Logged out</h1>
    <p>
        You have logged out!
    </p>
</div>
{% endblock %}

templates/accounts/reset_password.html
{% extends 'base.html' %}

{% block body %}
<div class="container">
    <h1>Password reset</h1>
    <p>
        Forgotten your password? Enter your email address below, and we'll email instructions for setting a new one.
    </p>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Reset password</button>
    </form>
</div>
{% endblock %}

templates/accounts/reset_password_complete.html
{% extends 'base.html' %}

{% block body %}
<div class="container">
    <h1>Password reset complete</h1>
    <a href="{% url 'smartlink:login' %}">Log in</a>
</div>
{% endblock %}

templates/accounts/reset_password_confirm.html
{% extends 'base.html' %}

{% block body %}
<div class="container">
    <h1>Enter new password</h1>
    <p>

    </p>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Reset password</button>
    </form>
</div>
{% endblock %}

templates/accounts/reset_password_done.html
{% extends 'base.html' %}

{% block body %}
<div class="container">
    <h1>Password reset sent</h1>
    <p>
        We've emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.

        If you don't receive an email, please make sure you've entered the address you registered with, and check your spam folder.
    </p>
</div>
{% endblock %}

templates/accounts/reset_password_email.html
{% load i18n %}{% autoescape off %}
{% blocktrans %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktrans %}

{% trans "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'smartlink:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% trans "Your username, in case you've forgotten:" %} {{ user.get_username }}

{% trans "Thanks for using our site!" %}

{% blocktrans %}The {{ site_name }} team{% endblocktrans %}

{% endautoescape %}